### ISSUE TITLE
Frequent test failures for JWTAuthPluginIntegrationTest

### ISSUE THREAD

**Issue by Raghavan1988** [torvalds-dev/solr#10]
Example:

Build: https://ci-builds.apache.org/job/Solr/job/Solr-Check-main/1053/

1 tests failed.
FAILED:  org.apache.solr.security.JWTAuthPluginIntegrationTest.mockOAuth2Server

Error Message:
org.junit.ComparisonFailure: Should have received 401 code expected:<[401]> but was:<[200]>

Stack Trace:
org.junit.ComparisonFailure: Should have received 401 code expected:<[401]> but was:<[200]>
 at __randomizedtesting.SeedInfo.seed([7827798BF4D91EFE:FF2798DB9165E212]:0)
 at org.junit.Assert.assertEquals(Assert.java:117)
 at org.apache.solr.security.JWTAuthPluginIntegrationTest.mockOAuth2Server(JWTAuthPluginIntegrationTest.java:143)
...
The other test failure is

org.apache.solr.security.JWTAuthPluginTest.initWithInvalidTrustedCertsFile

Failing for the past 1 build (Since #924 )
Took 7 ms.

Error Message
junit.framework.AssertionFailedError: Expected exception SolrException but no exception was thrown
Stacktrace
junit.framework.AssertionFailedError: Expected exception SolrException but no exception was thrown
	at __randomizedtesting.SeedInfo.seed([8651FF5FA6DE29A1:91C33C9AFD0459B5]:0)
	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2863)
	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2849)
	at org.apache.solr.security.JWTAuthPluginTest.initWithInvalidTrustedCertsFile(JWTAuthPluginTest.java:521)
...

**Comment by torvalds-dev** [comment]
torvalds.dev is analyzing the ticket

**Comment by torvalds-dev** [comment]
The issue you're facing is related to two test failures in the Apache Solr project. 

1. The first failure is in the `JWTAuthPluginIntegrationTest.mockOAuth2Server` test. The test expected a 401 HTTP status code, which usually signifies an unauthorized request, but it received a 200 status code, which signifies a successful request. This discrepancy caused the test to fail. 

2. The second failure is in the `JWTAuthPluginTest.initWithInvalidTrustedCertsFile` test. This test expected a `SolrException` to be thrown, but no exception was thrown, causing the test to fail.

To understand why these tests are failing, you would need to look at the test code and the code being tested. 

For the first test, the `mockOAuth2Server` method in `JWTAuthPluginIntegrationTest` is the one failing. This method is testing the JWT authentication plugin's interaction with a mock OAuth2 server. The test seems to be expecting a 401 unauthorized error, which suggests that it's testing the plugin's behavior when it receives an unauthorized response from the OAuth2 server. 

For the second test, the `initWithInvalidTrustedCertsFile` method in `JWTAuthPluginTest` is the one failing. This method is testing the JWT authentication plugin's initialization with an invalid trusted certificates file. The test is expecting a `SolrException` to be thrown, which suggests that it's testing the plugin's error handling when it's given an invalid certificates file.

To fix these tests, you would need to ensure that the code being tested behaves as expected in these scenarios. For the first test, you would need to ensure that the JWT authentication plugin correctly handles an unauthorized response from the OAuth2 server. For the second test, you would need to ensure that the JWT authentication plugin correctly throws a `SolrException` when it's initialized with an invalid certificates file. 

You might also want to check if there have been any recent changes to the code being tested or the test code itself that could have caused these tests to start failing. 

If you're still having trouble understanding why these tests are failing, you could try running the tests locally and adding additional logging or debugging to help identify the issue.
