### ISSUE TITLE
Frequent test failures for JWTAuthPluginIntegrationTest

### ISSUE THREAD

**Issue by torvalds-dev** [torvalds-dev/solr#42]
Example:

Build: https://ci-builds.apache.org/job/Solr/job/Solr-Check-main/1053/

1 tests failed.
FAILED: org.apache.solr.security.JWTAuthPluginIntegrationTest.mockOAuth2Server

Error Message:
org.junit.ComparisonFailure: Should have received 401 code expected:<[401]> but was:<[200]>

Stack Trace:
org.junit.ComparisonFailure: Should have received 401 code expected:<[401]> but was:<[200]>
at __randomizedtesting.SeedInfo.seed([7827798BF4D91EFE:FF2798DB9165E212]:0)
at org.junit.Assert.assertEquals(Assert.java:117)
at org.apache.solr.security.JWTAuthPluginIntegrationTest.mockOAuth2Server(JWTAuthPluginIntegrationTest.java:143)
...
The other test failure is

org.apache.solr.security.JWTAuthPluginTest.initWithInvalidTrustedCertsFile

Failing for the past 1 build (Since https://github.com/apache/solr/pull/924 )
Took 7 ms.

Error Message
junit.framework.AssertionFailedError: Expected exception SolrException but no exception was thrown
Stacktrace
junit.framework.AssertionFailedError: Expected exception SolrException but no exception was thrown
at __randomizedtesting.SeedInfo.seed([8651FF5FA6DE29A1:91C33C9AFD0459B5]:0)
at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2863)
at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2849)
at org.apache.solr.security.JWTAuthPluginTest.initWithInvalidTrustedCertsFile(JWTAuthPluginTest.java:521)
...

**Comment by torvalds-dev** [comment]
torvalds.dev is analyzing the ticket

**Comment by torvalds-dev** [comment]
The issue you're facing is related to two test failures in the Apache Solr project. 

1. The first failure is in the `JWTAuthPluginIntegrationTest.mockOAuth2Server` test. The test expected a 401 HTTP status code, which usually signifies an unauthorized request, but it received a 200 status code, which signifies a successful request. This discrepancy caused the test to fail. The test failure suggests that the mock OAuth2 server is not behaving as expected, possibly due to a misconfiguration or a bug in the code.

2. The second failure is in the `JWTAuthPluginTest.initWithInvalidTrustedCertsFile` test. This test expected a `SolrException` to be thrown, but no exception was thrown. This suggests that the JWTAuthPlugin is not correctly handling an invalid trusted certificates file.

The code you've provided is part of the `JWTAuthPluginIntegrationTest` class. It includes methods for creating a mock OAuth2 server and a security.json string. The `createMockOAuthServer` method initializes an SSL context and sets up a mock OAuth2 server with a given SSL certificate. The `createMockOAuthSecurityJson` method creates a security.json string that points to the mock OAuth2 server and trusts its SSL certificate.

To resolve these issues, you would need to investigate why the mock OAuth2 server is returning a 200 status code instead of a 401, and why the JWTAuthPlugin is not throwing a `SolrException` when initialized with an invalid trusted certificates file. This would likely involve debugging the test cases and the code under test, and possibly writing additional tests to isolate the problem.
